Add PULP_USE_UVLOOP envvar to activate uvloop in the content-app
pulp/pulp-service pull request #360
Opened 2024-11-25 15:09 UTC by pedro-psb

Experiement with `uvloop`: https://github.com/pulp/pulpcore/issues/6021

Setting `PULP_USE_UVLOOP` to anything will enable it, while not having is set uses the regular worker.

2024-11-27 14:36 UTC, pedro-psb commented
I dont know how to interpret/debug the konflux CI failure.

2024-11-28 17:37 UTC, decko commented
> I dont know how to interpret/debug the konflux CI failure.

It's Ok. It will keep failing and yet the build and deploy happens without issues.

2025-03-14 14:43 UTC, bmbouter commented on images/assets/patches/0013-Add-uvloop-as-the-the-Gunicorn-worker-eventloop.patch
> +
Would you be ok if this part of the diff is pulled out since we're declaring the dependency directly below?

2025-03-14 15:05 UTC, pedro-psb commented on images/assets/patches/0013-Add-uvloop-as-the-the-Gunicorn-worker-eventloop.patch
> +
Yes. In fact I was supposed to ask where was the right place at the time but I forget about it. Thanks for the input

2025-03-14 15:08 UTC, bmbouter requested changes
@pedro-psb I'll lgtm and merge when you push next. Ty!

2025-03-14 20:51 UTC, bmbouter commented
@pedro-psb I should have told you this earlier (sorry) but you also need to copy the patch to the container build and run it. See this example: https://github.com/pulp/pulp-service/pull/442/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R143

2025-03-17 14:46 UTC, merged